[FEAT] 구인마감 구현
MeeTeamNumdle/MeeTeam_BackEnd pull request #100
Opened 2024-03-19 10:05 UTC by mikekks

## 📝 PR 타입
- [x] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📝 반영 브랜치

- feat/
- closed #97

## 📝 변경 사항

- 구인마감 API 구현

## 📝 테스트 결과

<img width="449" alt="스크린샷 2024-03-19 오후 3 55 58" src="https://github.com/MeeTeamNumdle/MeeTeam_BackEnd/assets/100754581/ceaa951e-6feb-4ff9-9842-f0347c5e9491">

## 📝 To Reviewer

- 아직 인증 객체 관련 이슈는 해결 못했습니다.. 해결후에 컨트롤러 로직도 푸시할게요!

2024-03-20 04:19 UTC, Goder-0 requested changes
고생하셨습니다! 컨트롤러 부분 확인부탁드려요!

2024-03-20 08:44 UTC, mikekks commented on src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
> +        RecruitmentPost recruitmentPost = getRecruitmentPost(postId);
넵 좋습니다 어떻게 규칙화하는게 좋을까요??

2024-03-20 08:52 UTC, mikekks commented on src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
> +        recruitmentPost.closeRecruitmentPost();
흐음 저도 두 방식에서 고민이었는데요! getter 지양의 관점에서 getter를 사용하기보다 해당 객체에 메세지를 보내는게 더 객체지향적이지 않을까 싶어서 이렇게 진행했습니다!

2024-03-21 04:40 UTC, Goder-0 commented on src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
> +        recruitmentPost.closeRecruitmentPost();
앗 게터를 말씀드린게 아니였습니다!
`recruitmentPost.closeRecruitmentPost()` 메소드 자체가, 작성자가 같을 때 할 수 있다는 의미가 내포되어야 하는지에 대한 의문이었는데요!
`closeRecruimentPost` 메소드의 인자로 `userId`를 주고, `validateWriter`라는 private 메소드를 호출하여 검증로직을 캡슐화하는 것에 대해 여쭤본 것이었습니다. 이게 좋다 라기보다는 순수하게 어떻게 생각하시는지 궁금합니다!

2024-03-21 07:25 UTC, mikekks commented on src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
> +        recruitmentPost.closeRecruitmentPost();
아하 그러니까 validateWriter가 close 메서드 내부에 들어가면 어떨지에 대한 말씀이시군요? 좋은거 같아요! 캡슐화도 더 잘되는 것 같고요!

2024-03-24 06:41 UTC, merged